### ISSUE TITLE
Doesn't upload for files sizes greater than 150 MB

### ISSUE THREAD

**Issue by harsimrans** [harsimrans/DropboxSyncer#10]
Issue is: http://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload

Problem at Line: https://github.com/harsimrans/DropboxSyncer/blob/master/dropbox_sync/syncer.py#L115

**Comment by Shobhim** [comment]
Crashed while trying to upload a 300MB+ file.

error : OverflowError: string longer than 2147483647 bytes

**Comment by harsimrans** [comment]
commit eb7c8b17103e87703f0745f33aa1de32c7a23c07 now uploads files of any size.
